# Generated by Django 5.2.5 on 2025-09-23 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campagne',
            fields=[
                ('cod_anne', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('dat_debut', models.DateField()),
                ('dat_fin', models.DateField()),
                ('etat', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('id_candidat', models.AutoField(primary_key=True, serialize=False)),
                ('nom_cand', models.CharField(max_length=100)),
                ('pren_cand', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('dat_nais', models.DateField()),
                ('lieu_nais', models.CharField(max_length=255)),
                ('telephone1', models.CharField(max_length=20)),
                ('telephone2', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('sitmat', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Diplome',
            fields=[
                ('id_diplome', models.AutoField(primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Domaine',
            fields=[
                ('id_dom', models.AutoField(primary_key=True, serialize=False)),
                ('lib_dom', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id_dde', models.AutoField(primary_key=True, serialize=False)),
                ('dat_dde', models.DateField(auto_now_add=True)),
                ('cv', models.FileField(upload_to='cvs/')),
                ('diplome', models.CharField(max_length=255)),
                ('anne_obt_dip', models.PositiveSmallIntegerField()),
                ('etat_dde', models.CharField(choices=[('ENVOYEE', 'Envoyée'), ('EN_COURS', 'En cours'), ('ACCEPTEE', 'Acceptée'), ('REFUSEE', 'Refusée')], default='ENVOYEE', max_length=20)),
                ('reponse', models.TextField(blank=True, null=True)),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='recrutement.campagne')),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='recrutement.candidat')),
            ],
        ),
        migrations.AddField(
            model_name='candidat',
            name='diplome',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidats', to='recrutement.diplome'),
        ),
        migrations.AddField(
            model_name='diplome',
            name='domaine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diplomes', to='recrutement.domaine'),
        ),
    ]
