# Generated by Django 5.2.5 on 2025-09-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recrutement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidat',
            name='password',
            field=models.CharField(default='', max_length=128),
        ),
    ]
