# Generated by Django 5.2.5 on 2025-10-29 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recrutement', '0004_contactmessage_newsletter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demande',
            name='diplome',
        ),
        migrations.AddField(
            model_name='demande',
            name='diplome_fichier',
            field=models.FileField(blank=True, default='diplomes/default_diplome.pdf', null=True, upload_to='diplomes/'),
        ),
    ]
