# Generated by Django 5.2.5 on 2025-12-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recrutement', '0006_alter_contactmessage_prenom_cookieconsent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demande',
            name='reponse',
        ),
        migrations.AlterField(
            model_name='demande',
            name='etat_dde',
            field=models.CharField(choices=[('ENVOYEE', 'Envoyée'), ('EN COURS', 'En cours'), ('ACCEPTEE', 'Acceptée'), ('REFUSEE', 'Refusée')], default='ENVOYEE', max_length=20),
        ),
    ]
