# Generated by Django 5.2.5 on 2025-12-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recrutement', '0007_remove_demande_reponse_alter_demande_etat_dde'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='reponse',
            field=models.TextField(blank=True, null=True),
        ),
    ]
